language: php

php:
  - '7.0'
env:
  - SYMFONY_VERSION="3.1.*"

before_script:
    - mysql -e 'create database symfony;'
    - composer self-update
    - composer install

services:
    - mysql
 
script:
    - phpunit
